services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/db/mongodb-keyfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-config/mongodb-keyfile:/data/db/mongodb-keyfile:ro
    user: "999:999"

volumes:
  mongodb_data:
    driver: local
